package com.NegozioMusica.main.utils;

public enum TipoAmplificatore {
ACUSTICHE,COMBO_ELETTRICHE,TESTATA_ELETTRICHE,UNDODICESIMO,DUEDODICESIMI,QUATTRODODICESIMI,COMBO_BASSI,TESTATA_BASSI,UNQUINDICESIMO,DUEDECIMI,QUATTRODECIMI,OTTODECIMI,TASTIERE
}
