package com.NegozioMusica.main.utils;

public enum TipoCorde {
	OTTO, NOVE, DIECI, DIECIACUSTICHE, UNDICIACUSTICHE, UNDICI, DODICI, TREDICI, STANDARD, CARBONIO, STEEL, QUARANTA,
	QUARANTACINQUE, CINQUANTA, QUARANTACINQUECORDE, QUARANTACINQUECINQUECORDE, ACUSTICI
}
